# financial_policy_optimization
Optimization of the Financial Policy of the Polish Local Governments

Fiscal policy in Poland can be examined from two perspectives, the governmental central and social security subsectors and the local government subsector. Expenditures of those subsectors play an important role in the Polish economy, since they constitute together almost half of the gross domestic product. The aim of this dissertation was to assess the impact of fiscal rules on fiscal policy, including fiscal stability, in the general government (GG) sector, accounting for the specific features of its subsectors.

In the second part of this dissertation, hypotheses of an impact of the selected factors on the optimal level of current and investment expenditure of local government were verified, based on a novel optimization model of local goverment financial policy. The hypothesis about the postive impact of value of infrastructure on the current expenditure level was confirmed. It was also shown that an increase in: the rate of infrastructure depreciation, interest rate, debt level and the discount rate of future utility influence negatively the level of current expenditure. An unexpected effect was observed concerning the current expenditure incurred before the modeled period, namely higher past expenses reduce the space for current spending at the beginning of the considered period, but in the next year there is a compensation effect, i.e. former savings allow for higher expenditure than in a scenario without the savings. 

It was also found that an increase in the rate of infrastructure depreciation and the discount rate has a positive impact on the ordinary investment (i.e. not funded from the EU funds). Similarly, hypothesis was confirmed about a negative impact of: the interest rate, the debt maturity rate, the debt level and the value of infrastructure on ordinary investment. In the case of debt, however, there is a compensation effect - similar to the one described in the former paragraph. Such an effect occurs also for ordinary investment as a response variable and the past current expenditure as an explanatory variable. It turned out to be even stronger than for the current expenditure as a response variable. The optimal level of investment expenditure declines over time, which is a consequence of an adopted utility function. This function rewards investment realized earlier, because the infrastructure improved in this way is included several times in the utility. 

